### PR TITLE
Forms: make ligatures opt-in on inputs

### PR DESCRIPTION
**Pull request by kerryarchibald**
For https://github.com/vector-im/element-web/issues/25538

Adds `disableLigatures` prop to `Form.Text`
Default behaviour is for ligatures to match the rest of typography, ie enabled.

See:
- https://57d2e811.compound-web.pages.dev/?path=/story/typography--ligatures
- https://57d2e811.compound-web.pages.dev/?path=/story/form-controls-text--filled

### CODE REVIEW

**Review by weeman1337 — APPROVED** [review]
Looks good !

**Comment by t3chguy** [comment]
Hmm, IMO this should be more specific and less global, any input field which ends up being "sent" and then drawn like room name, topic, composer, etc would be confusing if it rendered differently

**Comment by kerryarchibald** [comment]
@t3chguy fair point, i've changed this to be a per-input `disableLigatures` property

**Comment by t3chguy** [comment]
@kerryarchibald great, what do you think about opt-in vs out?

**Pull request merged**
